### ISSUE TITLE
URL in the "GitHub repository" field triggers a redirect

### ISSUE THREAD

**Issue by alexislefebvre** [travis-ci/travis-yaml#50]
Entering an URL, like `https://github.com/travis-ci/travis-yaml` in the _Enter your Github repository_ field redirects to the URL instead of showing an error.

**Comment by edmorley** [comment]
I believe this needs to be filed against:
https://github.com/travis-ci/travis-weblint

(presuming that's still the active repo for the site)

**Comment by edmorley** [comment]
Filed https://github.com/travis-ci/travis-weblint/issues/14

**Comment by alexislefebvre** [comment]
Thanks @edmorley, I'll wait for some answer for issue or the linked one before closing this issue.
