### ISSUE TITLE
What does it mean? "your repository must be feature flagged for the os setting to be used"

### ISSUE THREAD

**Issue by RSATom** [travis-ci/travis-yaml#67]
I got this message when tried validate very basic config:

```
language: cpp
os: osx
```

**Comment by BanzaiMan** [comment]
This means that we detected the attempt to use the multi-os feature. See http://docs.travis-ci.com/user/multi-os/. The feature currently requires manual flip. If your repository has the feature enabled, you can ignore the warning. If you wish to have that feature enabled, pleas email support@travis-ci.com.

If you just want to use an OS X image, you should use `language: objective-c`(http://docs.travis-ci.com/user/languages/objective-c/).

**Comment by RSATom** [comment]
Thanks for response.
Now it's clear.

**Comment by RSATom** [comment]
It seems I do something totally wrong, even if I use 
```
language: objective-c
```
it still use ubuntu for build:
https://travis-ci.org/RSATom/WebChimera.js

**Comment by BanzaiMan** [comment]
Which build has `language: objective-c`?

**Comment by RSATom** [comment]
latest: https://github.com/RSATom/WebChimera.js/blob/wip/.travis.yml

**Comment by BanzaiMan** [comment]
@RSATom You have disabled the push builds for this repository (https://travis-ci.org/RSATom/WebChimera.js/requests) so the commit that last modified this file (https://github.com/RSATom/WebChimera.js/commit/27aa00e2c73d0e6dacc9933e3a8992b13b0fa726#diff-354f30a63fb0907d4ad57269548329e3) has not been tested.

I see that you are force pushing to the `wip` branch (https://travis-ci.org/RSATom/WebChimera.js/builds) but you can see that the commits we've tested do not have `language: objective-c`.

Re-enable push builds and try again. (You'll need to push a new commit.)

**Comment by RSATom** [comment]
Ah... sorry, my fault. Thank you.
