### ISSUE TITLE
No validation of project travis.yml in organization

### ISSUE THREAD

**Issue by SecUpwN** [travis-ci/travis-yaml#87]
Entering [our repository](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector) (which I recently moved into the new organization) into the URL validator at http://yaml.travis-ci.org, just redirects to our repository when pressing `Validate`. Please fix this behavior.

**Comment by BanzaiMan** [comment]
http://yaml.travis-ci.org/CellularPrivacy/Android-IMSI-Catcher-Detector says it has an error, where `deploy.file` is a sequence. This is a known issue (#59).

The redirect you describe is not happening, though. So I think we can close this issue.

**Comment by SecUpwN** [comment]
>The redirect you describe is not happening, though. So I think we can close this issue.

No, the redirect really is happening. I am using the [Tor-Browser](https://www.torproject.org/).

**Comment by BanzaiMan** [comment]
If redirect is happening, it is not our doing.

```
$ curl -I http://yaml.travis-ci.org/CellularPrivacy/Android-IMSI-Catcher-Detector
HTTP/1.1 200 OK 
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Content-Length: 3996
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Server: WEBrick/1.3.1 (Ruby/2.0.0/2015-12-16)
Date: Sun, 03 Apr 2016 18:36:52 GMT
Via: 1.1 vegur
```
